#!/usr/bin/env python
"""Emit the ProteinGym results tables as markdown, straight from the CSV + per-group npz.

Regenerate after any rerun so tables can never drift from the data:
    uv run --no-sync python report_proteingym.py > results/late_interaction/pilot_35m/benchmarks/PROTEINGYM_TABLES.md
"""
import csv
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from bootstrap_ci import boot_ci  # noqa: E402

D = Path("results/late_interaction/pilot_35m/benchmarks")
VARIANTS = ("dms_substitutions", "dms_indels", "clinical_substitutions", "clinical_indels")
METRIC = {"dms_substitutions": "Spearman", "dms_indels": "Spearman",
          "clinical_substitutions": "AUC", "clinical_indels": "AUC"}

# name -> (display, size, backbone-trained, scoring) — presentation order
ARMS = [
    ("esm2_35m_cosine",             "ESM-2 35M",                 "35M",  "pooled cosine"),
    ("esm2_35m_maxsim_untrained",   "ESM-2 35M",                 "35M",  "MaxSim (untrained, 480-D)"),
    ("esm2_late_35m_maxsim",        "ESM-2 35M + late train",    "35M",  "MaxSim (trained, 64-D)"),
    ("protsent_v2_dense",           "ProtSent-V2 35M",           "35M",  "pooled cosine"),
    ("v2_35m_maxsim_untrained",     "ProtSent-V2 35M",           "35M",  "MaxSim (untrained, 480-D)"),
    ("v2p5_35m_cosine",             "ProtSent-V2.5 35M",         "35M",  "pooled cosine"),
    ("proj128_late",                "ProtSent-V2 35M + late 4k", "35M",  "MaxSim (trained, 128-D)"),
    ("protsent_late_35m_prop_dense","ProtSent-V2 35M + late 31k","35M",  "pooled cosine"),
    ("protsent_late_35m_prop_late", "ProtSent-V2 35M + late 31k","35M",  "MaxSim (trained, 128-D)"),
    ("esm2_150m_cosine",            "ESM-2 150M",                "150M", "pooled cosine"),
    ("esm2_150m_maxsim_untrained",  "ESM-2 150M",                "150M", "MaxSim (untrained, 640-D)"),
    ("esm2_late_150m_maxsim",       "ESM-2 150M + late train",   "150M", "MaxSim (trained, 64-D)"),
    ("v2_150m_cosine",              "ProtSent-V2 150M",          "150M", "pooled cosine"),
    ("v2_150m_maxsim_untrained",    "ProtSent-V2 150M",          "150M", "MaxSim (untrained, 640-D)"),
    ("protsent_late_150m_maxsim",   "ProtSent-V2 150M + late 5k","150M", "MaxSim (trained, 64-D)"),
    ("protsent_late_150m_prop_late","ProtSent-V2 150M + late 30k","150M","MaxSim (trained, 128-D)"),
    ("protsent_late_150m_prop_dense","ProtSent-V2 150M + late 30k","150M","pooled cosine"),
]
NAMES = {n: (d, s, sc) for n, d, s, sc in ARMS}


def rows_by_variant():
    out = {}
    for r in csv.DictReader((D / "proteingym_maxsim.csv").open()):
        out.setdefault(r["variant"], {})[r["model"]] = r
    return out


def pq(variant, model):
    p = D / f"proteingym_{variant}_{model.replace('/', '_')}.npz"
    if not p.exists():
        return None
    z = np.load(p, allow_pickle=True)
    return dict(zip(z["assay"], z["score"]))


def paired(variant, a, b):
    x, y = pq(variant, a), pq(variant, b)
    if not x or not y:
        return None
    common = sorted(set(x) & set(y))
    d = np.array([x[k] - y[k] for k in common])
    mean, lo, hi = boot_ci(d, n_boot=2000, seed=42)
    return mean, lo, hi, len(common)


def fmt(delta):
    if delta is None:
        return "—"
    m, lo, hi, n = delta
    star = " \\*" if not (lo < 0 < hi) else ""
    return f"{m:+.4f} [{lo:+.4f}, {hi:+.4f}]{star}"


by = rows_by_variant()
print("<!-- generated by report_proteingym.py; regenerate, do not hand-edit -->\n")
for v in VARIANTS:
    if v not in by:
        continue
    m = by[v]
    n_groups = max(int(r["n_assays"]) for r in m.values())
    print(f"### ProteinGym {v.replace('_', ' ')} — mean {METRIC[v]} across {n_groups} "
          f"{'assays' if 'dms' in v else 'protein groups'}\n")
    print("| Model | Size | Scoring | " + METRIC[v] + " | 95% CI |")
    print("|---|---|---|---|---|")
    for name, disp, size, scoring in ARMS:
        if name not in m:
            continue
        r = m[name]
        print(f"| {disp} | {size} | {scoring} | {float(r['mean_score']):.4f} | {r['ci95']} |")
    print()
    print("Paired deltas (same groups, bootstrap over groups; \\* = 95% CI excludes zero):\n")
    print("| Comparison | Δ " + METRIC[v] + " |")
    print("|---|---|")
    for a, b, label in [
        ("esm2_35m_maxsim_untrained", "esm2_35m_cosine",  "MaxSim vs cosine, vanilla ESM-2 35M (same model)"),
        ("v2_35m_maxsim_untrained",  "protsent_v2_dense", "MaxSim vs cosine, ProtSent-V2 35M (same model)"),
        ("protsent_late_35m_prop_late", "protsent_late_35m_prop_dense", "MaxSim vs cosine, late-31k 35M (same model)"),
        ("proj128_late", "v2_35m_maxsim_untrained",       "Trained 128-D head vs untrained 480-D, ProtSent-V2 35M"),
        ("proj128_late", "esm2_35m_maxsim_untrained",     "ProtSent-V2 late-4k vs vanilla ESM-2 untrained MaxSim"),
        ("protsent_late_35m_prop_late", "proj128_late",   "31k continuation vs 4k arm (both MaxSim)"),
        ("v2_35m_maxsim_untrained", "esm2_35m_maxsim_untrained", "ProtSent-V2 vs vanilla ESM-2, both untrained MaxSim"),
        ("v2_150m_maxsim_untrained", "esm2_150m_maxsim_untrained","ProtSent-V2 vs vanilla ESM-2, both untrained MaxSim, 150M"),
        ("protsent_late_150m_prop_late", "v2_150m_maxsim_untrained", "150M late-30k vs untrained MaxSim"),
    ]:
        d = paired(v, a, b)
        if d is not None:
            print(f"| {label} | {fmt(d)} |")
    print()
